// <auto-generated />
namespace RedditClone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Communities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Communities));
        
        string IMigrationMetadata.Id
        {
            get { return "202001061825243_Communities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
